// Generated by CoffeeScript 1.6.3
(function() {
  exports.buildMessage = function(message) {
    return {
      date: new Date().toISOString(),
      message: message
    };
  };

  exports.random = function(items) {
    return items[Math.floor(Math.random() * items.length)];
  };

}).call(this);
